### ISSUE TITLE
"Problem" should be defined as objects 

### ISSUE THREAD

**Issue by arpcorrea** [ilyasst/consolidation-works#9]
There are several variables were not object-oriented. Some of them are even hard coded.

The code MUST avoid hard-codes and variables SHOULD be object-oriented whenever possible.

**Comment by ilyasst** [comment]
Not all variables must be objects. Objects should be used when relevant. If your class only has two attributes, it is a good sign that it might not be necessary. A dictionary or even list might be enough. Objects are especially convenient when we are talking about something that can be instantiated.

Let's put PR #8 aside for now as I do not think it is going to be helpful in the long run, we can take a look at why in more details. Please focus on #7 and more specifically on implementing the mask solution proposed in it.
